In [73]:
import pandas as pd
import numpy as np
import sklearn

In [81]:
df = pd.read_csv("hospital_readmissions.csv")
df.head()

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med,readmitted
0,[70-80),8,72,1,18,2,0,0,Missing,Circulatory,Respiratory,Other,no,no,no,yes,no
1,[70-80),3,34,2,13,0,0,0,Other,Other,Other,Other,no,no,no,yes,no
2,[50-60),5,45,0,18,0,0,0,Missing,Circulatory,Circulatory,Circulatory,no,no,yes,yes,yes
3,[70-80),2,36,0,12,1,0,0,Missing,Circulatory,Other,Diabetes,no,no,yes,yes,yes
4,[60-70),1,42,0,7,0,0,0,InternalMedicine,Other,Circulatory,Respiratory,no,no,no,yes,no

In [82]:
df.isna()

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med,readmitted
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [83]:
unique_values = df["medical_specialty"].unique()

In [77]:
from sklearn.preprocessing import LabelEncoder

In [78]:
categorical_vars = np.array(df[["medical_specialty", "diag_1", "diag_2", "diag_3"]])

In [79]:
encoder = LabelEncoder()

new_categorical_values = encoder.fit_transform(categorical_vars.reshape((-1,1)))

/Users/helloworld/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [80]:
df["medical_specialty", "diag_1", "diag_2", "diag_3"] = new_categorical_values

ValueError: Length of values (100000) does not match length of index (25000)

In [84]:
cat_columns = df.select_dtypes(['category']).columns

In [87]:
cat_columns

Index([], dtype='object')

In [85]:
df[cat_columns] = df[cat_columns].apply(lambda x: x.cat.codes)

In [86]:
df

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med,readmitted
0,[70-80),8,72,1,18,2,0,0,Missing,Circulatory,Respiratory,Other,no,no,no,yes,no
1,[70-80),3,34,2,13,0,0,0,Other,Other,Other,Other,no,no,no,yes,no
2,[50-60),5,45,0,18,0,0,0,Missing,Circulatory,Circulatory,Circulatory,no,no,yes,yes,yes
3,[70-80),2,36,0,12,1,0,0,Missing,Circulatory,Other,Diabetes,no,no,yes,yes,yes
4,[60-70),1,42,0,7,0,0,0,InternalMedicine,Other,Circulatory,Respiratory,no,no,no,yes,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,[80-90),14,77,1,30,0,0,0,Missing,Circulatory,Other,Circulatory,no,normal,no,no,yes
24996,[80-90),2,66,0,24,0,0,0,Missing,Digestive,Injury,Other,no,high,yes,yes,yes
24997,[70-80),5,12,0,6,0,1,0,Missing,Other,Other,Other,normal,no,no,no,yes
24998,[70-80),2,61,3,15,0,0,0,Family/GeneralPractice,Respiratory,Diabetes,Other,no,no,yes,yes,no
24999,[50-60),10,37,1,24,0,0,0,Missing,Other,Diabetes,Circulatory,no,no,no,no,yes

In [90]:
df[["medical_specialty", "diag_1", "diag_2", "diag_3"]] = df[["medical_specialty", "diag_1", "diag_2", "diag_3"]].apply(lambda x: encoder.fit_transform(x))

In [97]:
df[["glucose_test", "A1Ctest"]] = df[["glucose_test", "A1Ctest"]].apply(lambda x: encoder.fit_transform(x))

In [100]:
from sklearn.preprocessing import LabelBinarizer

In [101]:
binarizer = LabelBinarizer()

In [115]:
df[["change", "dietes_med", "readmitted"]]=df[["change", "diaetes_med", "readmitted"]].apply(lambda x: encoder.fit_transform(x))

KeyError: "['diaetes_med'] not in index"